fix(slider): bind the keydown event
opentiny/tiny-vue pull request #1038
Opened 2023-12-06 02:11 UTC by betavs

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #1024 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-06 02:15 UTC, betavs commented
@all-contributors please add @betavs for code

2023-12-06 06:55 UTC, yoyo201626 requested changes

2023-12-06 06:55 UTC, yoyo201626 commented on packages/renderless/src/slider/index.ts
> +  on(window, 'keydown', api.bindKeyDown)
不能在这给 `window` 加上`keydown`事件，这可能造成一个页面如果多个 Slider 组件，按一下快捷键，所有的slider都触发快捷键的动作，这不是预期的。
而且`bindKeyDown`函数已经在[模板](https://github.com/opentiny/tiny-vue/blob/dev/packages/vue/src/slider/src/pc.vue)里面绑定在锚点的`keydown`事件里面了。

2023-12-06 09:49 UTC, yoyo201626 requested changes

2023-12-06 09:49 UTC, yoyo201626 commented on packages/renderless/src/slider/index.ts
> +    event.preventDefault()
我觉得只要这一句代码就可以解决问题了

2023-12-06 09:49 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +      @mouseenter="bindMouseEnter"
我猜这里是想要鼠标移入的时快捷键就生效，但是我觉得没必要添加这个交互。

因为本文件的46行已经对锚点`class="tiny-slider__handle"`绑定快捷键事件了：
```
45        @mouseleave="hideTip"
46        @keydown="bindKeyDown"
47      >
```
目前聚焦到锚点时，快捷键就应该生效了

2023-12-08 08:36 UTC, yoyo201626 commented
@betavs 看一下

2023-12-08 08:39 UTC, betavs commented on packages/vue/src/slider/src/pc.vue
> +      @mouseenter="bindMouseEnter"
这个需要讨论一下吗

2023-12-08 09:23 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +      @mouseenter="bindMouseEnter"
可以讨论的。能说一下为什么加这个吗？我之前猜是想要鼠标移入的时快捷键就生效

2023-12-10 07:44 UTC, kagol commented
@betavs 感谢你的贡献，需要在 PR 标题中加上 `[slider]` 关键字，以便于自动跑 E2E 测试用例。
详细可参考贡献指南：
https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.zh-CN.md#pull-request-%E8%A7%84%E8%8C%83

```
运行e2e测试: 在提交信息里使用 [componentName1, componentName2]，将会执行componentName1，componentName2的测试用例，当改动的代码会影响组件时，需要声明这个结构。
```

2023-12-11 02:55 UTC, betavs commented on packages/vue/src/slider/src/pc.vue
> +      @mouseenter="bindMouseEnter"
是的，更好的交互体验

2023-12-11 03:30 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +      @mouseenter="bindMouseEnter"
挺好的想法。

不过应该先提一个Feature的Issue，把 fix 和 feature 分成不同的PR来提交。

这样也会给后面发版本时，汇总功能提供方便。

2023-12-11 06:18 UTC, yoyo201626 approved these changes

2023-12-14 08:03 UTC, zzcr approved these changes

2023-12-14 08:03 UTC, merged