Tiny theme
opentiny/tiny-vue pull request #1195
Opened 2023-12-21 10:31 UTC by James-9696

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ *] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [* ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [* ] No

## Other information

2023-12-22 07:47 UTC, chenxi-20 requested changes
建议先解决这些问题

2023-12-22 07:47 UTC, chenxi-20 commented on examples/sites/demos/pc/app/carousel/autoplay-composition-api.vue
> +  background-color: #fafafa;
这些示例的颜色值为什么要更改呢

2023-12-22 07:47 UTC, chenxi-20 commented on examples/sites/demos/pc/app/carousel/manual-play-composition-api.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
样式不能写内联，样式要全部放到类名底下去写

2023-12-22 07:47 UTC, chenxi-20 commented on examples/sites/demos/pc/app/carousel/manual-play.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
这里也是一样的：样式不能写内联，样式要全部放到类名底下去写

2023-12-22 07:47 UTC, chenxi-20 commented on packages/theme/src/theme.config.js
> +  'transfer': 'transfer'
transfer这种一个单词的，建议不在这里配

2023-12-22 07:47 UTC, chenxi-20 commented on packages/theme/src/carousel-item/smb-theme.js
> +  'ti-carousel-item-title-bg-color': '#dbdbdb'
#dbdbdb，这种值应该使用smb的基础变量即：--ti-common开头的，不能使用常量

2023-12-22 07:47 UTC, chenxi-20 commented on packages/theme/src/carousel/index.less
> +        opacity: var(--ti-carousel-outside-button-active-bg-color);
这里颜色值的变量不能赋值给opacity

2023-12-22 07:47 UTC, chenxi-20 commented on packages/theme/src/carousel/smb-theme.js
> +  // SMB主题
这个对象的键值只能写成var(--ti-common-XXX等形式的基础变量。不能写0.8或者#808080这样的常量值

2023-12-22 08:47 UTC, James-9696 commented on packages/theme/src/carousel/smb-theme.js
> +  // SMB主题
已修复

2023-12-22 08:47 UTC, James-9696 commented on packages/theme/src/carousel-item/smb-theme.js
> +  'ti-carousel-item-title-bg-color': '#dbdbdb'
已修复

2023-12-22 08:47 UTC, James-9696 commented on packages/theme/src/theme.config.js
> +  'transfer': 'transfer'
已修复

2023-12-22 08:48 UTC, James-9696 commented on examples/sites/demos/pc/app/carousel/manual-play.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
这个demo,方便用户查看，也可以在内联上写吧，不影响全局

2023-12-22 08:49 UTC, James-9696 commented on examples/sites/demos/pc/app/carousel/manual-play-composition-api.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
好的 我改成类样式

2023-12-22 09:00 UTC, James-9696 commented on packages/theme/src/carousel/index.less
> +        opacity: var(--ti-carousel-outside-button-active-bg-color);
已修复

2023-12-22 09:00 UTC, James-9696 commented on examples/sites/demos/pc/app/carousel/manual-play.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
已修复

2023-12-22 09:01 UTC, James-9696 commented on examples/sites/demos/pc/app/carousel/manual-play-composition-api.vue
> +    <div style="display: flex; justify-content: space-between; margin-top: 10px">
已修复

2023-12-22 09:02 UTC, James-9696 commented on examples/sites/demos/pc/app/carousel/autoplay-composition-api.vue
> +  background-color: #fafafa;
适配一下SMB的主题,所以改下demo的颜色

2023-12-25 11:22 UTC, chenxi-20 commented on examples/sites/demos/pc/app/carousel/autoplay-composition-api.vue
> +  background-color: #fafafa;
示例的颜色不建议更改

2023-12-27 09:48 UTC, gimmyhehe commented on packages/theme/src/transfer/smb-theme.js
> +  'ti-transfer-font-size': 'var(--ti-common-font-size-1)',
其他变量有默认值，这个变量是遗漏了么~

2023-12-27 09:49 UTC, Huangyilin19 approved these changes, later dismissed

2023-12-27 10:34 UTC, James-9696 commented on packages/theme/src/transfer/smb-theme.js
> +  'ti-transfer-font-size': 'var(--ti-common-font-size-1)',
已修改

2023-12-29 02:18 UTC, zzcr approved these changes

2023-12-29 02:18 UTC, merged