fix(slider): [slider] In input box mode, set the min attribute to a n…
opentiny/tiny-vue pull request #1202
Opened 2023-12-22 13:57 UTC by AcWrong02

…egative value and value to a negative value, and the % symbol should not be used.

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #1111 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-12-26 03:19 UTC, yoyo201626 requested changes

2023-12-26 03:19 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
这里不建议用“是否显示”来控制。
建议更加灵活的新增一个属性来自定义配置`%`的符号，比如温度，金钱的单位。

这样的话，当配置为`‘’`空字符时，也能实现“是否显示”的效果。
虽然当前已经有对应位置的插槽，但是这里如果能自定义配置符号，会比插槽更方便。

2023-12-26 03:19 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +    'showPercent',
新增的属性，需要在`packages/vue/src/slider/src/index.ts`同步新增

2023-12-26 03:19 UTC, yoyo201626 commented on examples/sites/demos/pc/app/slider/webdoc/slider.js
> +          'demoId': 'show-percent'
aip 下的 demoId字段需要与对应的demo下的demoId对应上，这里应该是`show-input`。

这里的demoId的作用是，当在官网点击api时会跳转到对应id的demo。

2023-12-26 03:19 UTC, yoyo201626 commented on examples/sites/demos/pc/app/slider/webdoc/slider.js
> +      'demoId': 'show-input',
修改了demo下的demoId，那么官网上对应demo的锚点值会改变了。
这将会影响到对应的e2e测试用例`show-iput.spec.ts`，需要同步修改测试用例。下面可以参考：

```ts
// examples/sites/demos/pc/app/slider/show-iput.spec.ts
4 ......
5 - await page.goto(‘slider#show-iput’)
5 + await page.goto(‘slider#show-input’)
......
```

2023-12-26 08:13 UTC, AcWrong02 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
收到，谢谢你的建议^V^

2024-01-04 07:01 UTC, kagol commented
@AcWrong02 记得解决下检视意见和E2E测试用例报错哈

2024-01-07 14:25 UTC, AcWrong02 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
我采用了原本index.ts中组件props上就有的unit属性，不知道合不合理？

2024-01-07 14:26 UTC, AcWrong02 commented
> @AcWrong02 记得解决下检视意见和E2E测试用例报错哈
> 
> E2E测试用例错误信息：https://github.com/opentiny/tiny-vue/actions/runs/7300642866/job/19934616322?pr=1202
> 
> ![image](https://private-user-images.githubusercontent.com/9566362/294108864-17bfa957-6f72-4b74-908e-46d509a073e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Mzc3NjMsIm5iZiI6MTcwNDYzNzQ2MywicGF0aCI6Ii85NTY2MzYyLzI5NDEwODg2NC0xN2JmYTk1Ny02ZjcyLTRiNzQtOTA4ZS00NmQ1MDlhMDczZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMTQyNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM2NGU5NzUwZjEzZDUxMzA5M2IyMzc2OTFlNzkyYWIzNWQwOGY1MDdiNzMyOTU4NDU4ZjU1ZjE5ZjUyOTI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gyBYl128OLSqJX7thXcxXbjVJAsDlal_7NZurh8nZCg)

不好意思，已经修改了

2024-01-07 14:27 UTC, AcWrong02 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
@yoyo201626 已做修改，辛苦再review一下

2024-01-10 09:54 UTC, yoyo201626 approved these changes

2024-01-10 09:55 UTC, yoyo201626 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
> 我采用了原本index.ts中组件props上就有的unit属性，不知道合不合理？

我觉得挺合理的

2024-01-10 09:56 UTC, yoyo201626 approved these changes

2024-01-10 12:39 UTC, AcWrong02 commented on packages/vue/src/slider/src/pc.vue
> +          /><span v-if="showPercent">%</span>
好的，谢谢

2024-01-15 02:10 UTC, zzcr approved these changes

2024-01-15 02:11 UTC, merged