fix(collapse): fix manually change the modelValue of a Collapse component, the change event does not trigger
opentiny/tiny-vue pull request #1308
Opened 2024-01-16 01:24 UTC by wkif

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-16 10:12 UTC, wuyiping0628 requested changes

2024-01-16 10:12 UTC, wuyiping0628 commented on examples/sites/demos/pc/app/collapse/events.vue
> +  <button @click="click">点击触发</button>
1.demo里面要使用tiny-button  2.events-composition-api.vue要同步修改

2024-01-16 10:23 UTC, wkif commented on examples/sites/demos/pc/app/collapse/events.vue
> +  <button @click="click">点击触发</button>
了解

2024-01-16 14:58 UTC, AcWrong02 commented on packages/vue/src/collapse/src/index.ts
这个change事件应该不用加在这里，before-close是要传给组件的prop没错，但是change是组件要emit的事件

2024-01-16 14:58 UTC, AcWrong02 commented on packages/renderless/src/collapse/vue.ts
考虑得全面一点的话，其实当activeNames.value.push('2')的时候，change事件也是不会触发的

2024-01-16 15:08 UTC, AcWrong02 commented on packages/renderless/src/collapse/vue.ts
我看element也有这个问题。。。感觉这种场景几乎不会出现

2024-01-17 02:45 UTC, AcWrong02 requested changes

2024-01-17 02:45 UTC, AcWrong02 commented on packages/renderless/src/collapse/vue.ts
另外，这样子当你点击collapse-item的时候是会触发两次change事件的

2024-01-17 06:29 UTC, wkif commented on packages/renderless/src/collapse/vue.ts
貌似没有好的解决思路了

2024-01-17 06:40 UTC, AcWrong02 commented on packages/renderless/src/collapse/vue.ts
导致触发两次change事件的原因是：你点击了collapse-item的时候会触发update:modeValue和change事件，触发了update:modeValue的时候，接下去就会触发watch里面的change事件。
可以尝试添加一个变量，判断是不是点击了collapse-item触发的change，如果是的话，就不触发watch中的change事件

2024-03-30 02:22 UTC, kagol commented
触发两次change事件的问题未解决，并且冲突长时间未解决

2024-03-30 02:22 UTC, closed without merging