fix(anchor):[anchor]When the anchor component has a default currentLink, the style is not the expected style
opentiny/tiny-vue pull request #1368
Opened 2024-02-03 01:38 UTC by fanbingbing16

…nk, the style is not the expected style

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #1366 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-02-04 03:20 UTC, chenxi-20 commented
这个是什么使用场景下会出现的问题，还请给出复现步骤~ @fanbingbing16

2024-02-04 03:21 UTC, chenxi-20 reviewed
这个是什么使用场景下会出现的问题，还请给出复现步骤~ @fanbingbing16

2024-02-04 03:24 UTC, chenxi-20 requested changes
1

2024-02-04 03:29 UTC, chenxi-20 commented on packages/renderless/src/anchor/index.ts
> +	state.currentLink && updateSkidPosition({ vm, state, emit })
这个是什么使用场景下会出现的问题，还请给出复现步骤~ @fanbingbing16

2024-02-04 03:30 UTC, chenxi-20 submitted a review, later dismissed

2024-02-04 03:46 UTC, fanbingbing16 commented on packages/renderless/src/anchor/index.ts
> +	state.currentLink && updateSkidPosition({ vm, state, emit })
Issue Number: https://github.com/opentiny/tiny-vue/issues/1366  可以查看这个issue

2024-02-04 06:23 UTC, chenxi-20 approved these changes, later dismissed

2024-02-04 06:24 UTC, chenxi-20 reviewed
好的，麻烦格式化一下代码，缩进不太对~

2024-02-04 08:47 UTC, fanbingbing16 commented
@chenxi-20 改好了

2024-02-05 02:26 UTC, chenxi-20 approved these changes

2024-02-05 03:28 UTC, zzcr approved these changes

2024-02-05 03:29 UTC, merged