(docs): update drag-outside-window of dialog-box
opentiny/tiny-vue pull request #1376
Opened 2024-02-05 03:58 UTC by James-9696

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [* ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [* ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [* ] No

## Other information

2024-02-05 04:16 UTC, AcWrong02 requested changes
默认值是false的话，这边使用true来进行演示是不是更合理一点呢？
另外，选项式api对应的文件draggable.vue对应的代码也需要一起修改一下

2024-02-05 06:29 UTC, James-9696 commented
已修改review建议

2024-02-06 08:58 UTC, gimmyhehe commented on examples/sites/demos/pc/app/dialog-box/webdoc/dialog-box.js
> +          '<p>可通过<code>draggable</code>属性设置<code>true</code>，鼠标点击标题区域拖拽；通过<code>drag-outside-window</code>属性设置<code>true</code>，将弹窗拖出窗口。具体事件：<code>@drag-start</code><code>@drag-move</code><code>@drag
文档整改规范，<code>draggable</code>两侧需要加个空格，如：
可通过 <code>draggable</code> 属性设置.....
这个问题可以先不改，后续可以统一走查一下责任田组件，一起改一下~

2024-02-06 09:00 UTC, James-9696 commented on examples/sites/demos/pc/app/dialog-box/webdoc/dialog-box.js
> +          '<p>可通过<code>draggable</code>属性设置<code>true</code>，鼠标点击标题区域拖拽；通过<code>drag-outside-window</code>属性设置<code>true</code>，将弹窗拖出窗口。具体事件：<code>@drag-start</code><code>@drag-move</code><code>@drag
好哒

2024-02-17 02:48 UTC, zzcr submitted a review, later dismissed

2024-02-20 06:37 UTC, kagol commented
@James-9696 麻烦解决下冲突

2024-02-20 07:36 UTC, James-9696 commented
冲突已解决

2024-02-20 11:19 UTC, kagol submitted a review, later dismissed

2024-02-20 11:41 UTC, kagol commented
@James-9696 
以下两个 demo 看不出区别：
![image](https://github.com/opentiny/tiny-vue/assets/9566362/cbcf853f-28cb-4695-8640-9dfdbe84a788)

我觉得这两个 demo，应该一个是只配置 `:draggable="true"`，用来演示可拖拽这个特性；另一个配置 `:draggable="true"` 和 `:drag-outside-window="true"`，用来演示可拖拽到窗口之外。

体验链接：
https://vercel.live/open-feedback/tiny-vue-git-fork-james-9696-pr-1268-fix-opentiny.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

2024-02-21 02:06 UTC, James-9696 commented
> @James-9696 以下两个 demo 看不出区别： ![image](https://private-user-images.githubusercontent.com/9566362/306247078-cbcf853f-28cb-4695-8640-9dfdbe84a788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODEzMTIsIm5iZiI6MTcwODQ4MTAxMiwicGF0aCI6Ii85NTY2MzYyLzMwNjI0NzA3OC1jYmNmODUzZi0yOGNiLTQ2OTUtODY0MC05ZGZkYmU4NGE3ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDIwMzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE5NDUwY2MyODgwOWFjOThhMDkwMTU4NWJmYmQ5Y2I3M2JkMzEyYWFiN2UwNzdkMDI4ODU1MmY0MjkwOTQwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9iIwg7MzsU1r6Vzv9STVSq35ZkILFQlypyIiORsjlBQ)
> 
> 我觉得这两个 demo，应该一个是只配置 `:draggable="true"`，用来演示可拖拽这个特性；另一个配置 `:draggable="true"` 和 `:drag-outside-window="true"`，用来演示可拖拽到窗口之外。
> 
> 体验链接： https://vercel.live/open-feedback/tiny-vue-git-fork-james-9696-pr-1268-fix-opentiny.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

demo已优化，可通过drag-outside-window配置看出区别

2024-02-27 02:20 UTC, zzcr approved these changes

2024-02-27 02:20 UTC, merged