test(grid): add grid header related unit test
opentiny/tiny-vue pull request #1737
Opened 2024-07-09 13:15 UTC by AcWrong02

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-07-09 14:45 UTC, kagol commented on packages/vue/src/grid/__tests__/grid.test.tsx
> +  test.skip('default-slot', async () => {
@AcWrong02 为什么跳过了这些用例呢？

2024-07-09 14:46 UTC, kagol commented
@AcWrong02 建议优先补充组件的E2E测试用例，而不是单元测试用例

2024-07-09 16:26 UTC, AcWrong02 commented on packages/vue/src/grid/__tests__/grid.test.tsx
> +  test.skip('default-slot', async () => {
在第一个pr中有编写，后面还需要进行整合

2024-07-22 02:26 UTC, Zcating requested changes
把两处代码先回滚一下吧，不用skip.

2024-08-05 14:58 UTC, closed without merging