refactor(grid-header): [grid]啊大大
opentiny/tiny-vue pull request #1744
Opened 2024-07-11 13:27 UTC by AcWrong02

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-07-11 15:05 UTC, Zcating requested changes

2024-07-11 15:05 UTC, Zcating commented on packages/renderless/types/grid/header.type.ts
不要新建文件夹，打平，grid-header.type.ts

2024-07-12 08:17 UTC, gimmyhehe commented on packages/vue/src/grid/src/header/src/pc.vue
> +  // Q：为什么要再定义出一个？有什么区别吗？
其实没有区别，我已经将部门这种用法改成了传递gridVm，然后在具体函数再解构

2024-07-12 10:14 UTC, AcWrong02 commented on packages/renderless/types/grid/header.type.ts
get

2024-07-22 02:17 UTC, Zcating approved these changes

2024-07-27 10:55 UTC, kagol commented
@AcWrong02 麻烦解决下冲突~
![image](https://github.com/user-attachments/assets/14cf6fde-1bc6-4ad1-8305-f23999a96b31)

2024-08-14 02:07 UTC, closed without merging