feat(rich-text-editor): fix bug, add font-size and add api demo
opentiny/tiny-vue pull request #497
Opened 2023-09-19 03:26 UTC by Caesar-ch

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
feat(rich-text-editor): fix bug, add font-size and add api demo
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-09-19 06:55 UTC, GaoNeng-wWw commented on examples/sites/demos/app/rich-text-editor/event-usage-composition-api.vue
> +}
这一部分最好使用Notify

2023-09-19 06:59 UTC, GaoNeng-wWw requested changes

2023-09-19 06:59 UTC, GaoNeng-wWw commented on packages/renderless/src/rich-text-edtior/index.ts
> +
```suggestion
```

2023-09-19 06:59 UTC, GaoNeng-wWw commented on examples/sites/demos/app/rich-text-editor/event-usage-composition-api.vue
> +}
这一段使用Notify组件更好，因为用户不一定会打开控制台

2023-09-19 06:59 UTC, GaoNeng-wWw commented on examples/sites/demos/app/rich-text-editor/event-usage.vue
> +    },
这一段使用Notify组件更好，因为用户不一定会打开控制台

2023-09-21 05:34 UTC, Caesar-ch commented on examples/sites/demos/app/rich-text-editor/event-usage.vue
> +    },
改了

2023-09-21 05:34 UTC, Caesar-ch commented on examples/sites/demos/app/rich-text-editor/event-usage-composition-api.vue
> +}
改了

2023-09-24 01:58 UTC, GaoNeng-wWw commented
有一个冲突需要解决一下 @Caesar-ch

2023-09-24 08:12 UTC, GaoNeng-wWw approved these changes

2023-09-24 08:20 UTC, merged