feat(react): Fix the React dev development link
opentiny/tiny-vue pull request #510
Opened 2023-09-25 02:35 UTC by pe-3

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

Fix the React dev development link.

2023-09-25 02:54 UTC, GaoNeng-wWw requested changes

2023-09-25 02:54 UTC, GaoNeng-wWw commented on internals/cli/src/commands/build/build-ui.ts
> +    // })
```suggestion
```

删除比注释更好

2023-09-25 02:54 UTC, GaoNeng-wWw commented on examples/react-docs/src/main.css
> +}
用了tailwind，是不是直接写className更好？

2023-09-25 02:54 UTC, GaoNeng-wWw commented on internals/cli/src/commands/build/build-ui-react.ts
> +
```suggestion
```

2023-09-25 02:54 UTC, GaoNeng-wWw commented on internals/cli/src/commands/build/build-ui.ts
> +    console.log(entry)
```suggestion
```

2023-09-25 02:54 UTC, GaoNeng-wWw commented on packages/react-common/src/vue-hooks.js
> +    isDepChange = true && immediate
这里的逻辑是不是冗余了

2023-09-25 02:54 UTC, GaoNeng-wWw commented on pnpm-lock.yaml
这个文件不要提交

2023-09-25 06:49 UTC, kagol commented on examples/react-docs/package.json
> +  "name": "@pe-3/react-docs",
别改这个

2023-09-25 06:50 UTC, kagol commented
@pe-3 不要提交 lock 文件

2023-09-25 08:40 UTC, pe-3 commented on examples/react-docs/src/main.css
> +}
好的，大哥

2023-09-25 08:40 UTC, pe-3 commented on packages/react-common/src/vue-hooks.js
> +    isDepChange = true && immediate
我都参考一下

2023-09-25 08:40 UTC, pe-3 commented on examples/react-docs/package.json
> +  "name": "@pe-3/react-docs",
好的

2023-09-25 08:40 UTC, pe-3 commented
> @pe-3 不要提交 lock 文件

好的

2023-09-27 13:33 UTC, kagol approved these changes

2023-09-27 13:34 UTC, merged