feat: scripts support cross-platform
opentiny/tiny-vue pull request #554
Opened 2023-10-04 10:08 UTC by gweesin

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Running scripts without error in Win OS.

Issue Number: #552 

## What is the new behavior?

scripts of `package.json` support cross-platform

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-04 13:47 UTC, GaoNeng-wWw requested changes

2023-10-04 13:47 UTC, GaoNeng-wWw commented on pnpm-lock.yaml
这个文件不要提交

2023-10-07 02:12 UTC, GaoNeng-wWw approved these changes

2023-10-07 02:44 UTC, kagol approved these changes

2023-10-07 02:44 UTC, merged