fix(vue-renderless): [cascader] fix cascader组件多选 配置 emitPath:false之后不回显选中名称
opentiny/tiny-vue pull request #844
Opened 2023-11-16 08:25 UTC by falcon-jin

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 843

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-11-16 10:40 UTC, yoyo201626 commented
测试场景
```vue
<template>
  <tiny-cascader v-model="value" :options="options" :props="{ emitPath: false, multiple: true }"></tiny-cascader>
</template>

<script setup>
import { ref } from 'vue'
import { Cascader as TinyCascader } from '@opentiny/vue'

const value = ref('')
const options = ref([
  {
    value: 'zhinan',
    label: '指南',
    children: [
      {
        value: 'anzhuang',
        label: '安装',
        children: [
          {
            value: 'xiangmudengji',
            label: '项目登记'
          },
          {
            value: 'huanjingzhunbei',
            label: '环境准备'
          },
          {
            value: 'anzhuangcli',
            label: '安装 CLI'
          },
          {
            value: 'chuangjianxiangmu',
            label: '创建项目'
          }
        ]
      }
    ]
  }
])
</script>
```
输入框不会回显：
![image](https://github.com/opentiny/tiny-vue/assets/104079404/816e2c98-8599-4c38-b8bd-ca5096276991)

2023-11-16 10:50 UTC, yoyo201626 requested changes
bug分析：
`checkedValue`在`emitPath=false && multiple=true`的情况下，是一个一维数组。
而原本的代码中，只考虑了二维数组的情况（`emitPath=false && multiple=true`），导致查找不到选中值

2023-11-16 10:50 UTC, yoyo201626 commented on packages/renderless/src/cascader-panel/index.ts
> +          if(checkedValue[i].length){
建议简化
```JavaScript
flag = checkedValue[i].length && checkedValue[i][checkedValue[i].length - 1] === str;
```

2023-11-16 10:55 UTC, yoyo201626 requested changes

2023-11-16 10:55 UTC, yoyo201626 commented on packages/renderless/src/cascader-panel/index.ts
> +        if (Array.isArray(checkedValue[i]) ) {
if语句后面多了个空格

2023-11-23 01:33 UTC, yoyo201626 approved these changes

2023-11-23 01:36 UTC, zzcr approved these changes

2023-11-23 01:36 UTC, merged

2023-12-11 06:39 UTC, kagol commented
@all-contributors please add @falcon-jin  for code

2024-01-08 08:53 UTC, kagol commented
@falcon-jin 恭喜你成为OpenTiny 2023年度开源新星，请添加下OpenTiny小助手微信：opentiny-official，如已添加，请发一条信息给小助手，谢谢！